name : Nicarali
brand : Nicarali
description : "Nicarali est une association qui opère pour la création d'un réseau de bibliothèques publiques au Nicaragua."
keyword : Nicarali, Nicaragua, bibliothèque, association
url : http://nicarali.com
cover: img/header-nica-modific3a9-21.jpg
email : nicarali@gmail.com
github : drventisette
facebook: nicarali
author : drventisette
analytics : UA-67806526-1
year : 2015
markdown : kramdown
exclude:
  - node_modules
  - bower_components/*.md
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate
paginate: 20
paginate_path: "/archive/page:num"
collections:
  news:
    output: true
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      lang: "fr"
  -
    scope:
      path: "_news/fr"
      type: "posts"
    values:
      lang: "fr"
  -
    scope:
      path: "_news/es"
      type: "posts"
    values:
      lang: "es"
